import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Check, Pause, Play, Radio, RefreshCw, SkipForward, Volume2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { useWorkspace } from '@/providers/WorkspaceProvider';
import { useWorkspaceRealtime } from '@/hooks/useWorkspaceRealtime';

type Player = { id: string; display_name: string | null; state: string; last_seen_at: string | null };
type Command = { id: string; command: string; status: string; created_at: string };
const db = supabase as any;
export function PlaybackPage() {
  const { workspace } = useWorkspace(); const { user } = useAuth(); const [players, setPlayers] = useState<Player[]>([]); const [selected, setSelected] = useState(''); const [commands, setCommands] = useState<Command[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { if (!db || !workspace) return; setLoading(true); const result = await db.from('players').select('id,display_name,state,last_seen_at').order('display_name'); const next = (result.data ?? []) as Player[]; setPlayers(next); setSelected(current => current && next.some(p => p.id === current) ? current : next[0]?.id ?? ''); if (selected) { const history = await db.from('player_commands').select('id,command,status,created_at').eq('player_id', selected).order('created_at', { ascending: false }).limit(8); setCommands((history.data ?? []) as Command[]); } setLoading(false); }, [workspace?.id, selected]);
  useEffect(() => { void load(); }, [load]); useWorkspaceRealtime(['players', 'player_commands'], load);
  const send = async (command: 'play' | 'pause' | 'skip') => { if (!db || !user || !selected) return; setBusy(true); setMessage(''); const result = await db.from('player_commands').insert({ player_id: selected, command, requested_by: user.id, status: 'pending', payload: {} }); setMessage(result.error?.message ?? `Command “${command}” queued.`); setBusy(false); if (!result.error) await load(); };
  const player = players.find(item => item.id === selected); const online = player?.state === 'online';
  return <div style={page}><header style={header}><div><p style={eyebrow}>PLAYBACK RUNTIME</p><h1 style={title}>Now playing</h1><p style={sub}>Send a command to a connected BranchCast player.</p></div><button style={button} onClick={() => void load()}><RefreshCw size={15}/> Refresh</button></header><section style={card}><label style={label}>Player<select style={select} value={selected} onChange={event => setSelected(event.target.value)}><option value="">Select a player</option>{players.map(item => <option value={item.id} key={item.id}>{item.display_name || 'Unnamed player'}</option>)}</select></label>{loading ? <p style={sub}>Loading player runtime…</p> : !player ? <div style={empty}><Radio size={24}/><strong>No player selected</strong><span>Register a player before sending playback commands.</span></div> : <><div style={now}><span style={art}><Radio size={24}/></span><div><small>PLAYER STATUS</small><h2>{player.display_name || 'Unnamed player'}</h2><p>{online ? 'Online and ready to receive commands.' : 'Offline. Commands are disabled until the next heartbeat.'}</p></div><span style={status(online)}>{online ? 'Online' : 'Offline'}</span></div><div style={controls}><button disabled={!online || busy} style={control} onClick={() => void send('play')}><Play size={17}/> Play</button><button disabled={!online || busy} style={control} onClick={() => void send('pause')}><Pause size={17}/> Pause</button><button disabled={!online || busy} style={control} onClick={() => void send('skip')}><SkipForward size={17}/> Skip</button><span style={volume}><Volume2 size={17}/> Remote command queue</span></div>{message && <p style={{ color: message.includes('queued') ? 'var(--success)' : 'var(--danger)', fontSize: 13 }}>{message}</p>}{!online && <p style={warning}><AlertTriangle size={15}/> Connect the player to enable remote playback commands.</p>}<div style={history}><strong>Recent commands</strong>{commands.length === 0 ? <p style={sub}>No commands sent for this player.</p> : commands.map(item => <div style={historyRow} key={item.id}><span>{item.command}</span><em>{item.status}</em><time>{new Date(item.created_at).toLocaleString()}</time></div>)}</div></>}</section></div>;
}
const page = { padding: '32px 40px', maxWidth: 1000, margin: '0 auto' } as const; const header = { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, flexWrap: 'wrap', marginBottom: 26 } as const; const eyebrow = { margin: 0, color: 'var(--signal)', fontWeight: 600, fontSize: 12, letterSpacing: '.06em' } as const; const title = { margin: '5px 0', fontSize: 28, color: 'var(--ink)' } as const; const sub = { margin: 0, color: 'var(--ink-secondary)', fontSize: 13 } as const; const button = { display: 'inline-flex', alignItems: 'center', gap: 7, border: '1px solid var(--border-color)', borderRadius: 8, padding: '10px 13px', background: '#fff', cursor: 'pointer' } as const; const card = { background: '#fff', border: '1px solid var(--border-color)', borderRadius: 14, padding: 22, marginTop: 26 } as const; const label = { display: 'grid', gap: 8, fontSize: 13, fontWeight: 600 } as const; const select = { border: '1px solid var(--border-color)', borderRadius: 8, padding: '11px 12px', background: '#fff', font: 'inherit', fontWeight: 400 } as const; const now = { display: 'flex', alignItems: 'center', gap: 15, marginTop: 26, padding: 20, background: 'var(--surface-subtle)', borderRadius: 12 } as const; const art = { width: 54, height: 54, display: 'grid', placeItems: 'center', borderRadius: 12, background: 'var(--signal)', color: '#fff', flexShrink: 0 } as const; const controls = { display: 'flex', alignItems: 'center', gap: 9, flexWrap: 'wrap', marginTop: 18 } as const; const control = { display: 'inline-flex', alignItems: 'center', gap: 6, border: '1px solid var(--border-color)', borderRadius: 8, padding: '10px 13px', background: '#fff', cursor: 'pointer' } as const; const volume = { display: 'inline-flex', alignItems: 'center', gap: 6, marginLeft: 'auto', color: 'var(--ink-secondary)', fontSize: 13 } as const; const empty = { display: 'grid', placeItems: 'center', gap: 8, padding: 48, color: 'var(--ink-secondary)', textAlign: 'center' } as const; const warning = { display: 'flex', alignItems: 'center', gap: 7, color: 'var(--danger)', fontSize: 13, marginTop: 18 } as const; const status = (online: boolean) => ({ marginLeft: 'auto', borderRadius: 99, padding: '5px 9px', fontSize: 11, color: online ? 'var(--success)' : 'var(--danger)', background: online ? 'rgba(44,167,96,.10)' : 'rgba(210,63,63,.08)' }) as const; const history = { marginTop: 24, borderTop: '1px solid var(--border-color)', paddingTop: 16 } as const; const historyRow = { display: 'grid', gridTemplateColumns: '1fr 100px 1.6fr', gap: 10, padding: '10px 0', borderBottom: '1px solid var(--border-color)', fontSize: 12 } as const;
